### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Kelvin-K-Cho** [Kelvin-K-Cho/hallyu#2]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds
- [x] Demo login

**Comment by dwebster17** [comment]
Let's put a demo login so recruiters can easily explore your site

**Comment by dwebster17** [comment]
Right now logging out redirects to a `stations` route. Is this desired functionality, or would it make more sense to redirect back to the root/welcome page?

**Comment by dwebster17** [comment]
When I log out, the "log out" button still shows

**Comment by dwebster17** [comment]
Must have been an issue of somebody else logging in at the same time. Works now
