### ISSUE TITLE
PA Review: Stations

### ISSUE THREAD

**Issue by Kelvin-K-Cho** [Kelvin-K-Cho/hallyu#3]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Basic CRUD 
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by dwebster17** [comment]
For the image upload on stations, you shouldn't be asking users to provide an image url. Rather, you should have an `<input type='file' />` that allows users to upload an image themselves. You will then add the file attachments on the backend the same way you added a file attachment to your users. Tracks will also need file attachments for audio.

**Comment by Kelvin-K-Cho** [comment]
Updated web app to accept image uploads for stations.

**Comment by dwebster17** [comment]
I tried to create a station and got errors. Please fix!

**Comment by dwebster17** [comment]
Working now
